<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Austin’s MB Projects - BIOSTAT 719 - Homework 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Austin’s MB Projects</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About Austin’s MB Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link active" data-scroll-target="#problem-1">Problem 1</a></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2">Problem 2</a></li>
  <li><a href="#problem-3" id="toc-problem-3" class="nav-link" data-scroll-target="#problem-3">Problem 3</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BIOSTAT 719 - Homework 3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1">Problem 1</h2>
<p>As in Homework 1, consider 150 observations <span class="math inline">\(Y_i, i = 1, . . . , 150\)</span>, from the exponential distribution:</p>
<p><span class="math display">\[
f(y_i; \lambda) = \lambda e^{-\lambda y_i}, \quad y_i &gt; 0, \lambda &gt; 0
\]</span></p>
<p>with the sum of these 150 observations equal to 30.</p>
<p><strong>Part (a):</strong> Starting from <span class="math inline">\(\lambda_{\text{start}} = 1\)</span> obtain the next iteration of the Newton-Raphson algorithm. Show details of your work. Do NOT use computer.</p>
<p>Recall that the score function for a set of independent exponential random variables is <span class="math inline">\(U = \frac{d\ell}{d\lambda} = \frac{n}{\lambda} - \sum_{i = 1}^n y_i\)</span>. Thus, <span class="math inline">\(U' = -\frac{n}{\lambda^2}\)</span>. We also know that <span class="math inline">\(\lambda_1 = \lambda_{\text{start}} - \frac{U_{\text{start}}}{U'_{\text{start}}}\)</span>. Plugging and chugging, we can see:</p>
<p><span class="math display">\[\begin{align*}
\lambda_1 &amp;= \lambda_{\text{start}} - \frac{U_{\text{start}}}{U'_{\text{start}}}\\
&amp;= 1 - \frac{\frac{n}{1} - \sum y_i}{-\frac{n}{1^2}}\\
&amp;= 1 - \frac{150 - 30}{-150}\\
&amp;= 1.8
\end{align*}\]</span></p>
<p>Here we have the after one iteration of the Newton-Raphson algoritm, <span class="math inline">\(\lambda_1 = 1.8\)</span>.</p>
<p><strong>Part (b):</strong> Starting from <span class="math inline">\(\lambda_{\text{start}} = 1\)</span> obtain the next iteration of the Method of Scoring algorithm. Show details of your work. Do NOT use computer.</p>
<p>The formula for the method of score algorithm is this: <span class="math inline">\(\lambda_1 = \lambda_{\text{start}} + \frac{U_{\text{start}}}{I(\lambda)_{\text{start}}}\)</span>. This being the case, we need to find the Fisher’s information for <span class="math inline">\(\lambda\)</span>. I’m going to use the fact that the exponential distribution belongs to the exponential family to help me solve this:</p>
<p><span class="math display">\[\begin{align*}
I(\lambda_i) &amp;= \frac{b''(\lambda_i)c'(\lambda_i)}{b'(\lambda_i)} - c''(\lambda_i)\\
b(\lambda_i) &amp;= -\lambda_i\\
b'(\lambda_i) &amp;= -1\\
b''(\lambda_i) &amp;= 0\\
c(\lambda_i) &amp;= log(\lambda_i)\\
c'(\lambda_i) &amp;= \frac{1}{\lambda_i}\\
c''(\lambda_i) &amp;= -\frac{1}{\lambda_i^2}\\
I(\lambda_i) &amp;= \frac{b''(\lambda_i)c'(\lambda_i)}{b'(\lambda_i)} - c''(\lambda_i)\\
&amp;= \frac{(0)(1/\lambda_i)}{-1} - \left(-\frac{1}{\lambda_i^2}\right)\\
&amp;= \frac{1}{\lambda_i^2}\\
\end{align*}\]</span></p>
<p>Because each <span class="math inline">\(y_i\)</span> is i.i.d., <span class="math inline">\(\lambda_i\)</span> is equivalent and we can add the information for each <span class="math inline">\(\lambda_i\)</span> quite easily:</p>
<p><span class="math display">\[\begin{align*}
I(\lambda_{\text{start}}) &amp;= \sum_{i = 1}^n I(\lambda_i)\\
&amp;= \sum_{i = 1}^n \frac{1}{\lambda^2}\\
&amp;= \sum_{i = 1}^n \frac{1}{1^2}\\
&amp;= n
\end{align*}\]</span></p>
<p>We know from the previous example that <span class="math inline">\(U = \frac{n}{\lambda} - \sum_{i = 1}^n y_i\)</span>. Thus,</p>
<p><span class="math display">\[\begin{align*}
\lambda_1 &amp;= \lambda_{start} + \frac{U}{I(\lambda_{\text{start}})}\\
&amp;= \lambda_{start} + \frac{\frac{n}{\lambda} - \sum_{i = 1}^n y_i}{n}\\
&amp;= 1 + \frac{\frac{150}{1} - 30}{150}\\
&amp;= 1 + 0.8\\
&amp;= 1.8
\end{align*}\]</span></p>
<p><strong>Part (c):</strong> Are your answers in (1) and (2) different? Explain why.</p>
<p>They are the same! This is because the exponential distribution belongs to the exponential family and has the canonical form, so <span class="math inline">\(I(\lambda) = -U'(\lambda)\)</span>. Thus, each will evaluate to the same value.</p>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2">Problem 2</h2>
<p>Suppose <span class="math inline">\(Y_1, . . . , Y_n\)</span> are independent random variables following the normal distribution <span class="math inline">\(Y_i \sim N(\log(\beta), \sigma^2)\)</span>, where <span class="math inline">\(\sigma^2\)</span> is known. Derive matrix based formula for an iteratively re-weighted least squares (IRWLS) procedure for ML estimation of <span class="math inline">\(\beta\)</span>.</p>
<p>[Hint: first, present matrices X and W, and vector for the formula <span class="math inline">\(b^{(m)} = \left( X^TW^{(m - 1)}X \right)^{-1}X^TW^{(m - 1)}z^{(m-1)}\)</span>, and then simplify this formula as feasible.]</p>
<p>The first thing that I will note is that <span class="math inline">\(\mu = \log(\beta)\)</span>. This implies two things. First, <span class="math inline">\(\log(\beta) = \log(X^T\beta)\)</span>, which implies that <span class="math inline">\(X_{n\times 1} = \left[\begin{matrix} 1\\1\\...\\1 \end{matrix}\right]\)</span>, and that <span class="math inline">\(\beta_{1\times 1} = \left[\begin{matrix} \beta_0 \end{matrix}\right]\)</span>. The second implication is that because <span class="math inline">\(\mu = \log(\beta)\)</span>, <span class="math inline">\(g(\mu) = \exp(\beta)\)</span>.</p>
<p>Let’s now calculate <span class="math inline">\(w_i\)</span> for the diagonal matrix <span class="math inline">\(W\)</span>:</p>
<p><span class="math display">\[\begin{align*}
w_i &amp;= \frac{1}{Var(Y_i)}\left(\frac{\partial \mu_i}{\partial \eta_i}\right)^2\\
&amp;= \frac{1}{\sigma^2} \left(\frac{1}{\beta} \right)^2\\
\begin{bmatrix}
\frac{1}{\sigma^2\beta^2} &amp; 0 &amp; \cdots &amp; 0\\
0 &amp; \frac{1}{\sigma^2\beta^2} &amp; \cdots &amp; 0 \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \cdots &amp; \frac{1}{\sigma^2\beta^2}
\end{bmatrix}
\end{align*}\]</span></p>
<p>The next thing to calculate is the <span class="math inline">\(z\)</span> vector. Recall that <span class="math inline">\(z_i = \sum_{k = 1}^p x_{ik}b_i^{(m -1)} + (y_i - \mu_i)\left(\frac{\partial  \eta_i}{\partial \mu_i} \right)\)</span>. Note that because we only have a single parameter, and because the <span class="math inline">\(X\)</span> matrix is a <span class="math inline">\(n\times 1\)</span> matrix of <span class="math inline">\(1\)</span>’s, <span class="math inline">\(\sum_{k = 1}^p x_{ik}b_i^{(m -1)}\)</span> simplifies to <span class="math inline">\(b^{(m - 1)}\)</span> (denoted below as <span class="math inline">\(\beta\)</span>).</p>
<p><span class="math display">\[\begin{align*}
z_i &amp;= \beta + (y_i - \mu_i) \frac{\partial\eta_i}{\partial \mu_i}\\
&amp;= \beta + [y_i - \log(\beta)]\beta\\
\implies z &amp;= \beta + Y\beta - \log(\beta)\beta\\
&amp;= \beta\left(1 + Y - \log(\beta)\right)
\end{align*}\]</span></p>
<p>This gives rise to the following matrix based formula for an teratively re-weighted procedure for ML estimation of <span class="math inline">\(\beta\)</span>:</p>
<p><span class="math display">\[\begin{align*}
b^{(m)} &amp;= \left( X^TW^{(m - 1)}X \right)^{-1}X^TW^{(m - 1)}z^{(m-1)}\\
&amp;= \left(
    \begin{bmatrix}1 \cdots 1\end{bmatrix}\frac{1}{\beta^2\sigma^2}I
    \begin{bmatrix}1\\ \vdots \\1\end{bmatrix}
    \right)^{-1}
    \begin{bmatrix}1 \cdots 1\end{bmatrix} \frac{1}{\beta^2\sigma^2}I \beta\left(1 + Y - \log(\beta)\right)\\
&amp;= \left(\frac{n}{\beta^2\sigma^2}\right)^{-1}\frac{1}{\beta^2\sigma^2}\begin{bmatrix}1 \cdots 1\end{bmatrix} \beta\left(1 + Y - \log(\beta)\right)\\
&amp;= \frac{1}{n}\begin{bmatrix}\beta\cdots\beta\end{bmatrix}(1 + Y - \log(\beta))
\end{align*}\]</span></p>
</section>
<section id="problem-3" class="level2">
<h2 class="anchored" data-anchor-id="problem-3">Problem 3</h2>
<p>Consider Table 4.3 [Textbook page 67] discussed in class. We now use a log link function.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>yi</strong></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>xi</strong></td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Part (a):</strong> Fit the model <span class="math inline">\(\log(E(Y_i)) = \beta_0 + \beta_1x_i\)</span> with the GLM function in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the data</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>yi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">15</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>xi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(yi <span class="sc">~</span> xi, <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model and point estimates </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>table_title <span class="ot">&lt;-</span> <span class="st">"Model: E(Y) = beta0 + beta1 X"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>b_0 <span class="ot">&lt;-</span> <span class="fu">round</span>(poisson_model<span class="sc">$</span>coefficients[<span class="dv">1</span>], <span class="dv">3</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">round</span>(poisson_model<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="dv">3</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>model_table <span class="ot">&lt;-</span> gt<span class="sc">::</span><span class="fu">gt</span>(</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">Parameter =</span> <span class="fu">c</span>(<span class="st">"beta0"</span>, <span class="st">"beta1"</span>), <span class="at">Estimate =</span> <span class="fu">c</span>(b_0, b_1))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)  <span class="sc">%&gt;%</span> </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    gt<span class="sc">::</span><span class="fu">tab_header</span>(<span class="at">title =</span> table_title)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;div id="akflneuchm" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;"&gt;
  &lt;style&gt;#akflneuchm table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#akflneuchm thead, #akflneuchm tbody, #akflneuchm tfoot, #akflneuchm tr, #akflneuchm td, #akflneuchm th {
  border-style: none;
}

#akflneuchm p {
  margin: 0;
  padding: 0;
}

#akflneuchm .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#akflneuchm .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#akflneuchm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#akflneuchm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#akflneuchm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#akflneuchm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#akflneuchm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#akflneuchm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#akflneuchm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#akflneuchm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#akflneuchm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#akflneuchm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#akflneuchm .gt_spanner_row {
  border-bottom-style: hidden;
}

#akflneuchm .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#akflneuchm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#akflneuchm .gt_from_md &gt; :first-child {
  margin-top: 0;
}

#akflneuchm .gt_from_md &gt; :last-child {
  margin-bottom: 0;
}

#akflneuchm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#akflneuchm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#akflneuchm .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#akflneuchm .gt_row_group_first td {
  border-top-width: 2px;
}

#akflneuchm .gt_row_group_first th {
  border-top-width: 2px;
}

#akflneuchm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#akflneuchm .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#akflneuchm .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#akflneuchm .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#akflneuchm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#akflneuchm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#akflneuchm .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#akflneuchm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#akflneuchm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#akflneuchm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#akflneuchm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#akflneuchm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#akflneuchm .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#akflneuchm .gt_left {
  text-align: left;
}

#akflneuchm .gt_center {
  text-align: center;
}

#akflneuchm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#akflneuchm .gt_font_normal {
  font-weight: normal;
}

#akflneuchm .gt_font_bold {
  font-weight: bold;
}

#akflneuchm .gt_font_italic {
  font-style: italic;
}

#akflneuchm .gt_super {
  font-size: 65%;
}

#akflneuchm .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#akflneuchm .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#akflneuchm .gt_indent_1 {
  text-indent: 5px;
}

#akflneuchm .gt_indent_2 {
  text-indent: 10px;
}

#akflneuchm .gt_indent_3 {
  text-indent: 15px;
}

#akflneuchm .gt_indent_4 {
  text-indent: 20px;
}

#akflneuchm .gt_indent_5 {
  text-indent: 25px;
}
&lt;/style&gt;
  &lt;table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"&gt;
  &lt;thead&gt;
    &lt;tr class="gt_heading"&gt;
      &lt;td colspan="2" class="gt_heading gt_title gt_font_normal gt_bottom_border" style&gt;Model: E(Y) = beta0 + beta1 X&lt;/td&gt;
    &lt;/tr&gt;
    
    &lt;tr class="gt_col_headings"&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Parameter"&gt;Parameter&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Estimate"&gt;Estimate&lt;/th&gt;
    &lt;/tr&gt;
  &lt;/thead&gt;
  &lt;tbody class="gt_table_body"&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;beta0&lt;/td&gt;
&lt;td headers="Estimate" class="gt_row gt_right"&gt;1.889&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;beta1&lt;/td&gt;
&lt;td headers="Estimate" class="gt_row gt_right"&gt;0.670&lt;/td&gt;&lt;/tr&gt;
  &lt;/tbody&gt;
  
  
&lt;/table&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Part (b):</strong> We want to obtain:</p>
<ol type="1">
<li>Maximum likelihood estimates for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span></li>
<li>Variance-covariance matrix of the MLE for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span></li>
</ol>
<p>Write an iteratively reweighted least squares R function similar to the one covered in class but accounting for the <strong>log link</strong>. In addition, provide all the details of the algebraic derivations.</p>
<p>Let’s first derive the important terms:</p>
<ul>
<li><span class="math inline">\(n = 9\)</span></li>
<li><span class="math inline">\(p = 2\)</span></li>
<li><span class="math inline">\(\beta = \begin{bmatrix} \beta_0\\ \beta_1\end{bmatrix}\)</span></li>
<li><span class="math inline">\(X^T = \begin{bmatrix} 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \\-1 &amp; -1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 1 &amp; 1 \end{bmatrix}\)</span></li>
<li><span class="math inline">\(\log(\mu) = \eta \implies \mu = e^{\eta}\)</span></li>
<li><span class="math inline">\(\frac{\partial \eta}{\partial\mu} = \frac{1}{e^{\eta}}\)</span></li>
<li><span class="math inline">\(\frac{\partial \mu}{\partial\eta} = e^{\eta}\)</span></li>
<li><span class="math inline">\(w_{ii} = \frac{1}{Var(Y_i)}\left(\frac{\partial \mu}{\partial\eta}\right)^2 = \frac{\exp[(2)(\beta_0 + \beta_1x_i)]}{(\beta_0 + \beta_1x_i)}\)</span></li>
<li><span class="math inline">\(z_i = \eta_i + (y_i - e^{\eta_i})e^{-\eta_i} = \beta_0 + \beta_1 x_i + \frac{y_i}{ e^{\beta_0 + \beta_1 x_i}} - 1\)</span></li>
<li><span class="math inline">\(I = X^TWX = \begin{bmatrix} \sum_{i = 1}^n \frac{\exp[(2)(\beta_0 + \beta_1x_i)]}{(\beta_0 + \beta_1x_i)} &amp; \sum_{i = 1}^n \frac{x_i\exp[(2)(\beta_0 + \beta_1x_i)]}{(\beta_0 + \beta_1x_i)} \\\sum_{i = 1}^n \frac{x_i\exp[(2)(\beta_0 + \beta_1x_i)]}{(\beta_0 + \beta_1x_i)} &amp; \sum_{i = 1}^n \frac{x_i^2\exp[(2)(\beta_0 + \beta_1x_i)]}{(\beta_0 + \beta_1x_i)}\end{bmatrix}\)</span></li>
<li><span class="math inline">\(X^T Wz = \begin{bmatrix} \sum_{i = 1}^n w_iz_i\\ \sum_{i = 1}^n w_ix_iz_i \end{bmatrix}\)</span></li>
</ul>
<p>With this setup, we can implement our algorithm in R. I’m going to use the same initial values of 7 and 5 used in class for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">####################################### R #####################################</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define function to find w_ii </span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="cf">function</span>(y_i, x_i, b_0, b_1) {</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">exp</span>((b_0 <span class="sc">+</span> b_1<span class="sc">*</span>x_i)))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Define function to find z_i </span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="cf">function</span>(y_i, x_i, b_0, b_1) {</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(b_0 <span class="sc">+</span> b_1<span class="sc">*</span>x_i <span class="sc">+</span> y_i<span class="sc">/</span>(<span class="fu">exp</span>(b_0 <span class="sc">+</span> b_1<span class="sc">*</span>x_i)) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Define function to estimate b_0 and b_1 </span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>mle_estimation <span class="ot">&lt;-</span> <span class="cf">function</span>(y_i, x_i, w, z, b_0_init, b_1_init, n_iterations) {</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># y_i: vector of outcome variable </span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># x_i: vector of 1 predictor (how could we generalize this?)</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># w: function to find w_ii from y_i, x_i, b_0, and b_1 </span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># z: function to find z_i from y_i, x_i, b_0, and b_1 </span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># b_0_init: initial value for b_0 estimate used in first iteration </span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># b_1_init: initial value for b_1 estimate used in first iteration </span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># n_iterations: number of cycles to run (could it be more useful to use </span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># while loop instead of for loop?)</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define vector of estimates </span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    b <span class="ot">&lt;-</span> <span class="fu">c</span>(b_0_init, b_1_init)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define matrix to be returned </span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    stored_estimates <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">numeric</span>(n_iterations<span class="sc">*</span><span class="dv">2</span>), <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Perform IRWLS procedure to estimate the MLEs for \beta_0 and \beta_1</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_iterations) {</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>        b_0 <span class="ot">&lt;-</span> b[<span class="dv">1</span>]</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>        b_1 <span class="ot">&lt;-</span> b[<span class="dv">2</span>]</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>        x_matrix <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">length</span>(x_i)), x_i)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Find w_ii and z_i </span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>        w_ii <span class="ot">&lt;-</span> <span class="fu">w</span>(y_i, x_i, b_0, b_1)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>        z_i  <span class="ot">&lt;-</span> <span class="fu">z</span>(y_i, x_i, b_0, b_1)</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>        <span class="co"># For readability, think of (X^T W X)^-1 as matrix_a and (X^T W z) as </span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>        <span class="co"># matrix_b</span></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>        matrix_a <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(x_matrix) <span class="sc">%*%</span> <span class="fu">diag</span>(w_ii) <span class="sc">%*%</span> x_matrix)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>        matrix_b <span class="ot">&lt;-</span> <span class="fu">t</span>(x_matrix) <span class="sc">%*%</span> <span class="fu">diag</span>(w_ii) <span class="sc">%*%</span> z_i</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>        b <span class="ot">&lt;-</span> matrix_a <span class="sc">%*%</span> matrix_b </span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>        stored_estimates[i, ] <span class="ot">&lt;-</span> b</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(stored_estimates)</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Record data for analysis </span></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>y_i <span class="ot">&lt;-</span>  <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">15</span>)</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>x_i <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Set initial values for b_0 and b_1 </span></span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>b_0_init <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>b_1_init <span class="ot">&lt;-</span> <span class="dv">7</span> </span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Use IRWLS to estimate b_0 and b_1 </span></span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">mle_estimation</span>(y_i, x_i, w, z, b_0_init, b_1_init, <span class="dv">15</span>)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results in a pretty table </span></span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>b_table <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(b)  <span class="sc">%&gt;%</span> </span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>        <span class="at">Iteration =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>,</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>        <span class="at">Beta0 =</span> V1,</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>        <span class="at">Beta1 =</span> V2</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>    )  <span class="sc">%&gt;%</span> </span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Iteration, Beta0, Beta1)  <span class="sc">%&gt;%</span> </span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a>    gt<span class="sc">::</span><span class="fu">gt</span>()  <span class="sc">%&gt;%</span> </span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a>    gt<span class="sc">::</span><span class="fu">tab_header</span>(</span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"Results: Estimates for Beta0 and Beta1 in IRWLS Procedure"</span></span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(b_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;div id="curudhnmdj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;"&gt;
  &lt;style&gt;#curudhnmdj table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#curudhnmdj thead, #curudhnmdj tbody, #curudhnmdj tfoot, #curudhnmdj tr, #curudhnmdj td, #curudhnmdj th {
  border-style: none;
}

#curudhnmdj p {
  margin: 0;
  padding: 0;
}

#curudhnmdj .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#curudhnmdj .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#curudhnmdj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#curudhnmdj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#curudhnmdj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#curudhnmdj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#curudhnmdj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#curudhnmdj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#curudhnmdj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#curudhnmdj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#curudhnmdj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#curudhnmdj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#curudhnmdj .gt_spanner_row {
  border-bottom-style: hidden;
}

#curudhnmdj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#curudhnmdj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#curudhnmdj .gt_from_md &gt; :first-child {
  margin-top: 0;
}

#curudhnmdj .gt_from_md &gt; :last-child {
  margin-bottom: 0;
}

#curudhnmdj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#curudhnmdj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#curudhnmdj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#curudhnmdj .gt_row_group_first td {
  border-top-width: 2px;
}

#curudhnmdj .gt_row_group_first th {
  border-top-width: 2px;
}

#curudhnmdj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#curudhnmdj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#curudhnmdj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#curudhnmdj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#curudhnmdj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#curudhnmdj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#curudhnmdj .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#curudhnmdj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#curudhnmdj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#curudhnmdj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#curudhnmdj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#curudhnmdj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#curudhnmdj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#curudhnmdj .gt_left {
  text-align: left;
}

#curudhnmdj .gt_center {
  text-align: center;
}

#curudhnmdj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#curudhnmdj .gt_font_normal {
  font-weight: normal;
}

#curudhnmdj .gt_font_bold {
  font-weight: bold;
}

#curudhnmdj .gt_font_italic {
  font-style: italic;
}

#curudhnmdj .gt_super {
  font-size: 65%;
}

#curudhnmdj .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#curudhnmdj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#curudhnmdj .gt_indent_1 {
  text-indent: 5px;
}

#curudhnmdj .gt_indent_2 {
  text-indent: 10px;
}

#curudhnmdj .gt_indent_3 {
  text-indent: 15px;
}

#curudhnmdj .gt_indent_4 {
  text-indent: 20px;
}

#curudhnmdj .gt_indent_5 {
  text-indent: 25px;
}
&lt;/style&gt;
  &lt;table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"&gt;
  &lt;thead&gt;
    &lt;tr class="gt_heading"&gt;
      &lt;td colspan="3" class="gt_heading gt_title gt_font_normal gt_bottom_border" style&gt;Results: Estimates for Beta0 and Beta1 in IRWLS Procedure&lt;/td&gt;
    &lt;/tr&gt;
    
    &lt;tr class="gt_col_headings"&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Iteration"&gt;Iteration&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Beta0"&gt;Beta0&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Beta1"&gt;Beta1&lt;/th&gt;
    &lt;/tr&gt;
  &lt;/thead&gt;
  &lt;tbody class="gt_table_body"&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;1&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;4.067257&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;6.9328087&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;2&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;3.238167&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;6.7620773&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;3&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;2.629619&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;6.3711097&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;4&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;2.348223&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;5.6538244&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;5&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;2.296974&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;4.7086591&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;6&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;2.284874&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;3.7305386&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;7&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;2.256773&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;2.7854100&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;8&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;2.192685&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;1.9229649&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;9&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;2.078582&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;1.2335379&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;10&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;1.954098&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.8196265&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;11&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;1.895948&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.6832292&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;12&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;1.889336&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.6699088&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;13&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;1.889272&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.6697856&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;14&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;1.889272&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.6697856&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Iteration" class="gt_row gt_right"&gt;15&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;1.889272&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.6697856&lt;/td&gt;&lt;/tr&gt;
  &lt;/tbody&gt;
  
  
&lt;/table&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It looks like we converge at iteration 13. Not too bad! Our MLE estimates are 1.889 for <span class="math inline">\(\beta_0\)</span> and 0.670 for <span class="math inline">\(\beta_1\)</span>.</p>
<p>Let’s now get the Information matrix to solve for the variance-covariance matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Recall that I = X^T W X </span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set parameters and calculate w_ii </span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>b_0 <span class="ot">&lt;-</span> <span class="fl">1.889272</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fl">0.6697856</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>x_matrix <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">9</span>), x_i)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>w_ii <span class="ot">&lt;-</span> <span class="fu">w</span>(y_i, x_i, b_0, b_1)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate I </span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="fu">t</span>(x_matrix) <span class="sc">%*%</span> <span class="fu">diag</span>(w_ii) <span class="sc">%*%</span> x_matrix </span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate variance-covariance matrix </span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>var_cov_matrix <span class="ot">&lt;-</span> <span class="fu">solve</span>(i)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(var_cov_matrix) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Beta0"</span>, <span class="st">"Beta1"</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(var_cov_matrix) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Beta0"</span>, <span class="st">"Beta1"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>var_cov_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(var_cov_matrix)  <span class="sc">%&gt;%</span> </span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">"Parameter"</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Print table </span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>var_cov_table <span class="ot">&lt;-</span> var_cov_df  <span class="sc">%&gt;%</span> </span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    gt<span class="sc">::</span><span class="fu">gt</span>()  <span class="sc">%&gt;%</span> </span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    gt<span class="sc">::</span><span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"Variance-Covariance Matrix"</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var_cov_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;div id="tgvvjqizgv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;"&gt;
  &lt;style&gt;#tgvvjqizgv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#tgvvjqizgv thead, #tgvvjqizgv tbody, #tgvvjqizgv tfoot, #tgvvjqizgv tr, #tgvvjqizgv td, #tgvvjqizgv th {
  border-style: none;
}

#tgvvjqizgv p {
  margin: 0;
  padding: 0;
}

#tgvvjqizgv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#tgvvjqizgv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#tgvvjqizgv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#tgvvjqizgv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#tgvvjqizgv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tgvvjqizgv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tgvvjqizgv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tgvvjqizgv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#tgvvjqizgv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#tgvvjqizgv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#tgvvjqizgv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#tgvvjqizgv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#tgvvjqizgv .gt_spanner_row {
  border-bottom-style: hidden;
}

#tgvvjqizgv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#tgvvjqizgv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#tgvvjqizgv .gt_from_md &gt; :first-child {
  margin-top: 0;
}

#tgvvjqizgv .gt_from_md &gt; :last-child {
  margin-bottom: 0;
}

#tgvvjqizgv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#tgvvjqizgv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#tgvvjqizgv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#tgvvjqizgv .gt_row_group_first td {
  border-top-width: 2px;
}

#tgvvjqizgv .gt_row_group_first th {
  border-top-width: 2px;
}

#tgvvjqizgv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tgvvjqizgv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#tgvvjqizgv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#tgvvjqizgv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tgvvjqizgv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tgvvjqizgv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#tgvvjqizgv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#tgvvjqizgv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#tgvvjqizgv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tgvvjqizgv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tgvvjqizgv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tgvvjqizgv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tgvvjqizgv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tgvvjqizgv .gt_left {
  text-align: left;
}

#tgvvjqizgv .gt_center {
  text-align: center;
}

#tgvvjqizgv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#tgvvjqizgv .gt_font_normal {
  font-weight: normal;
}

#tgvvjqizgv .gt_font_bold {
  font-weight: bold;
}

#tgvvjqizgv .gt_font_italic {
  font-style: italic;
}

#tgvvjqizgv .gt_super {
  font-size: 65%;
}

#tgvvjqizgv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#tgvvjqizgv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#tgvvjqizgv .gt_indent_1 {
  text-indent: 5px;
}

#tgvvjqizgv .gt_indent_2 {
  text-indent: 10px;
}

#tgvvjqizgv .gt_indent_3 {
  text-indent: 15px;
}

#tgvvjqizgv .gt_indent_4 {
  text-indent: 20px;
}

#tgvvjqizgv .gt_indent_5 {
  text-indent: 25px;
}
&lt;/style&gt;
  &lt;table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"&gt;
  &lt;thead&gt;
    &lt;tr class="gt_heading"&gt;
      &lt;td colspan="3" class="gt_heading gt_title gt_font_normal gt_bottom_border" style&gt;Variance-Covariance Matrix&lt;/td&gt;
    &lt;/tr&gt;
    
    &lt;tr class="gt_col_headings"&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Parameter"&gt;Parameter&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Beta0"&gt;Beta0&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Beta1"&gt;Beta1&lt;/th&gt;
    &lt;/tr&gt;
  &lt;/thead&gt;
  &lt;tbody class="gt_table_body"&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;Beta0&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;0.02019584&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;-0.01419063&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;Beta1&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;-0.01419063&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.03192892&lt;/td&gt;&lt;/tr&gt;
  &lt;/tbody&gt;
  
  
&lt;/table&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Part (c):</strong> Compare values obtained in (a) and (b).</p>
<p>Let’s print the tables from our model in part a:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table for the var_cov_matrix</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>model_var_cov_matrix <span class="ot">&lt;-</span> <span class="fu">summary</span>(poisson_model)<span class="sc">$</span>cov.unscaled</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(model_var_cov_matrix) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Beta0"</span>, <span class="st">"Beta1"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(model_var_cov_matrix) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Beta0"</span>, <span class="st">"Beta1"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>model_var_cov_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(model_var_cov_matrix)  <span class="sc">%&gt;%</span> </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">"Parameter"</span>) </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>model_var_cov_table <span class="ot">&lt;-</span> model_var_cov_df  <span class="sc">%&gt;%</span> </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    gt<span class="sc">::</span><span class="fu">gt</span>()  <span class="sc">%&gt;%</span> </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    gt<span class="sc">::</span><span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"Variance-Covariance Matrix"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print both tables </span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;div id="avjvtfdmdg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;"&gt;
  &lt;style&gt;#avjvtfdmdg table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#avjvtfdmdg thead, #avjvtfdmdg tbody, #avjvtfdmdg tfoot, #avjvtfdmdg tr, #avjvtfdmdg td, #avjvtfdmdg th {
  border-style: none;
}

#avjvtfdmdg p {
  margin: 0;
  padding: 0;
}

#avjvtfdmdg .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#avjvtfdmdg .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#avjvtfdmdg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#avjvtfdmdg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#avjvtfdmdg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#avjvtfdmdg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#avjvtfdmdg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#avjvtfdmdg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#avjvtfdmdg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#avjvtfdmdg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#avjvtfdmdg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#avjvtfdmdg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#avjvtfdmdg .gt_spanner_row {
  border-bottom-style: hidden;
}

#avjvtfdmdg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#avjvtfdmdg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#avjvtfdmdg .gt_from_md &gt; :first-child {
  margin-top: 0;
}

#avjvtfdmdg .gt_from_md &gt; :last-child {
  margin-bottom: 0;
}

#avjvtfdmdg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#avjvtfdmdg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#avjvtfdmdg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#avjvtfdmdg .gt_row_group_first td {
  border-top-width: 2px;
}

#avjvtfdmdg .gt_row_group_first th {
  border-top-width: 2px;
}

#avjvtfdmdg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#avjvtfdmdg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#avjvtfdmdg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#avjvtfdmdg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#avjvtfdmdg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#avjvtfdmdg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#avjvtfdmdg .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#avjvtfdmdg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#avjvtfdmdg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#avjvtfdmdg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#avjvtfdmdg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#avjvtfdmdg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#avjvtfdmdg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#avjvtfdmdg .gt_left {
  text-align: left;
}

#avjvtfdmdg .gt_center {
  text-align: center;
}

#avjvtfdmdg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#avjvtfdmdg .gt_font_normal {
  font-weight: normal;
}

#avjvtfdmdg .gt_font_bold {
  font-weight: bold;
}

#avjvtfdmdg .gt_font_italic {
  font-style: italic;
}

#avjvtfdmdg .gt_super {
  font-size: 65%;
}

#avjvtfdmdg .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#avjvtfdmdg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#avjvtfdmdg .gt_indent_1 {
  text-indent: 5px;
}

#avjvtfdmdg .gt_indent_2 {
  text-indent: 10px;
}

#avjvtfdmdg .gt_indent_3 {
  text-indent: 15px;
}

#avjvtfdmdg .gt_indent_4 {
  text-indent: 20px;
}

#avjvtfdmdg .gt_indent_5 {
  text-indent: 25px;
}
&lt;/style&gt;
  &lt;table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"&gt;
  &lt;thead&gt;
    &lt;tr class="gt_heading"&gt;
      &lt;td colspan="2" class="gt_heading gt_title gt_font_normal gt_bottom_border" style&gt;Model: E(Y) = beta0 + beta1 X&lt;/td&gt;
    &lt;/tr&gt;
    
    &lt;tr class="gt_col_headings"&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Parameter"&gt;Parameter&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Estimate"&gt;Estimate&lt;/th&gt;
    &lt;/tr&gt;
  &lt;/thead&gt;
  &lt;tbody class="gt_table_body"&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;beta0&lt;/td&gt;
&lt;td headers="Estimate" class="gt_row gt_right"&gt;1.889&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;beta1&lt;/td&gt;
&lt;td headers="Estimate" class="gt_row gt_right"&gt;0.670&lt;/td&gt;&lt;/tr&gt;
  &lt;/tbody&gt;
  
  
&lt;/table&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_var_cov_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;div id="kostbujlox" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;"&gt;
  &lt;style&gt;#kostbujlox table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#kostbujlox thead, #kostbujlox tbody, #kostbujlox tfoot, #kostbujlox tr, #kostbujlox td, #kostbujlox th {
  border-style: none;
}

#kostbujlox p {
  margin: 0;
  padding: 0;
}

#kostbujlox .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#kostbujlox .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#kostbujlox .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kostbujlox .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kostbujlox .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kostbujlox .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kostbujlox .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kostbujlox .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#kostbujlox .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#kostbujlox .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#kostbujlox .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#kostbujlox .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#kostbujlox .gt_spanner_row {
  border-bottom-style: hidden;
}

#kostbujlox .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#kostbujlox .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#kostbujlox .gt_from_md &gt; :first-child {
  margin-top: 0;
}

#kostbujlox .gt_from_md &gt; :last-child {
  margin-bottom: 0;
}

#kostbujlox .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#kostbujlox .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#kostbujlox .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#kostbujlox .gt_row_group_first td {
  border-top-width: 2px;
}

#kostbujlox .gt_row_group_first th {
  border-top-width: 2px;
}

#kostbujlox .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kostbujlox .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#kostbujlox .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#kostbujlox .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kostbujlox .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kostbujlox .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#kostbujlox .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#kostbujlox .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#kostbujlox .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kostbujlox .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kostbujlox .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kostbujlox .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kostbujlox .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kostbujlox .gt_left {
  text-align: left;
}

#kostbujlox .gt_center {
  text-align: center;
}

#kostbujlox .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kostbujlox .gt_font_normal {
  font-weight: normal;
}

#kostbujlox .gt_font_bold {
  font-weight: bold;
}

#kostbujlox .gt_font_italic {
  font-style: italic;
}

#kostbujlox .gt_super {
  font-size: 65%;
}

#kostbujlox .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#kostbujlox .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#kostbujlox .gt_indent_1 {
  text-indent: 5px;
}

#kostbujlox .gt_indent_2 {
  text-indent: 10px;
}

#kostbujlox .gt_indent_3 {
  text-indent: 15px;
}

#kostbujlox .gt_indent_4 {
  text-indent: 20px;
}

#kostbujlox .gt_indent_5 {
  text-indent: 25px;
}
&lt;/style&gt;
  &lt;table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"&gt;
  &lt;thead&gt;
    &lt;tr class="gt_heading"&gt;
      &lt;td colspan="3" class="gt_heading gt_title gt_font_normal gt_bottom_border" style&gt;Variance-Covariance Matrix&lt;/td&gt;
    &lt;/tr&gt;
    
    &lt;tr class="gt_col_headings"&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Parameter"&gt;Parameter&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Beta0"&gt;Beta0&lt;/th&gt;
      &lt;th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Beta1"&gt;Beta1&lt;/th&gt;
    &lt;/tr&gt;
  &lt;/thead&gt;
  &lt;tbody class="gt_table_body"&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;Beta0&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;0.02019583&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;-0.01419063&lt;/td&gt;&lt;/tr&gt;
    &lt;tr&gt;&lt;td headers="Parameter" class="gt_row gt_left"&gt;Beta1&lt;/td&gt;
&lt;td headers="Beta0" class="gt_row gt_right"&gt;-0.01419063&lt;/td&gt;
&lt;td headers="Beta1" class="gt_row gt_right"&gt;0.03192891&lt;/td&gt;&lt;/tr&gt;
  &lt;/tbody&gt;
  
  
&lt;/table&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We are pretty much spot on! That’s amazing. Both our estimates match (rounded to three decimals), and the same is true of the variance-covariance matrix. All in a day’s work.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>