<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Austin’s MB Projects - BIOSTAT 719 - Homework 6</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Austin’s MB Projects</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About Austin’s MB Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link active" data-scroll-target="#problem-1">Problem 1</a></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2">Problem 2</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BIOSTAT 719 - Homework 6</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1">Problem 1</h2>
<p>The following table shows an illustrative dataset with variables defined as below.</p>
<ul>
<li>y: number of hospitalization</li>
<li>n: total number of patients</li>
<li>Treatment: 0 = Drug A, 1 = Drug B</li>
<li>Disease severity: 0 = mild, 1 = Modeate, 2 = Severe</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Y</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">Treatment</th>
<th style="text-align: center;">DiseaseSeverity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">51</td>
<td style="text-align: center;">200</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">67</td>
<td style="text-align: center;">158</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">42</td>
<td style="text-align: center;">89</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">143</td>
<td style="text-align: center;">315</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">97</td>
<td style="text-align: center;">263</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">40</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We want to answer the following three scientific questions:</p>
<p>• Question 1: Which treatment is better to prevent (or lower) hospitalization?</p>
<p>• Question 2: Is the disease severity associated with hospitalization?</p>
<p>• Question 3: Does the treatment effect differ by disease severity? (i.e., Is the disease severity an effect moderator?)</p>
<p>We consider three logistic models with different sets of explanatory variables. We consider “treatment” as a categorical variable and “disease severity” as a continuous variable.</p>
<p>• Model 1 includes treatment only.</p>
<p>• Model 2 includes disease severity only.</p>
<p>• Model 3 includes treatment, disease severity, and treatment-by-disease severity interaction.</p>
<ol type="a">
<li>How many parameters does the saturated logistic regression model have? Explain fully.</li>
</ol>
<blockquote class="blockquote">
<p>The saturated model contains 6 parameters. This is because the length of <span class="math inline">\(Y\)</span> is 6, and the saturated model has one parameter for each observation of <span class="math inline">\(Y\)</span>.</p>
</blockquote>
<ol start="2" type="a">
<li>Write down the three logistic regression models.</li>
</ol>
<blockquote class="blockquote">
<p>Model 1: <span class="math inline">\(\log\left(\frac{\pi}{1 - \pi}\right) = \beta_0 + \beta_1 \text{Treatment}\)</span> Model 2: <span class="math inline">\(\log\left(\frac{\pi}{1 - \pi}\right) = \beta_0 + \beta_1 \text{DiseaseSeverity}\)</span> Model 3: <span class="math inline">\(\log\left(\frac{\pi}{1 - \pi}\right) = \beta_0 + \beta_1 \text{Treatment} + \beta_2\text{DiseaseSeverity} + \beta_3\text{Treatment}\cdot\text{DiseaseSeverity}\)</span></p>
</blockquote>
<ol start="3" type="a">
<li>Which model is suitable to answer each of the three scientific questions? E.g., Model X is suitable to answer Question X.</li>
</ol>
<blockquote class="blockquote">
<ul>
<li>Model 1 (treatment only) is suitable to answer question 1 (is treatment associated with y?).</li>
<li>Model 2 (disease severity only) is suitable to answer question 2 (is disease severity associated with y?).</li>
<li>Model 3 (including interaction) is suitable to answer question 3 (does treatment differ across varying values of disease severity?).</li>
<li>It appears that model # and question # are highly correlated!</li>
</ul>
</blockquote>
<ol start="4" type="a">
<li>Fit the three logistic models using R or SAS. Provide your code and output.</li>
</ol>
<blockquote class="blockquote">
<p>I’m going to do this in three stages, so the output isn’t so jumbled. Let’s start with model 1.</p>
</blockquote>
<hr>
<section id="model-1-cbindy-n---y-treatment" class="level4">
<h4 class="anchored" data-anchor-id="model-1-cbindy-n---y-treatment">Model 1: cbind(Y, N - Y) ~ Treatment</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify data</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>disease_severity <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">51</span>, <span class="dv">67</span>, <span class="dv">42</span>, <span class="dv">143</span>, <span class="dv">97</span>, <span class="dv">40</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">200</span>, <span class="dv">158</span>, <span class="dv">89</span>, <span class="dv">315</span>, <span class="dv">263</span>, <span class="dv">75</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into a dataframe</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>hospitalizations <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y =</span> y, <span class="at">N =</span> n, <span class="at">Treatment =</span> treatment, <span class="at">DiseaseSeverity =</span> disease_severity</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>model_1_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cbind</span>(Y, N <span class="sc">-</span> Y) <span class="sc">~</span> Treatment,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> hospitalizations</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Now that we’ve fit the model, let’s look at the model using R’s <code>summary</code> function:</p>
</blockquote>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(Y, N - Y) ~ Treatment, family = binomial(link = "logit"), 
    data = hospitalizations)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.58431    0.09866  -5.922 3.17e-09 ***
Treatment    0.29752    0.12644   2.353   0.0186 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 31.120  on 5  degrees of freedom
Residual deviance: 25.544  on 4  degrees of freedom
AIC: 62.382

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>I know this section isn’t for interpretation, but heck, I’m going to interpret the results. It does look like there is a significant increase in the odds of hospitalization in treatment group B (treatment = 1) compared to treatment group A (treatment = 0). The 95% confidence interval for the OR is [1.05, 1.72], with a point estimate of 1.34. Thus, the odds of hospitalization are 34% higher in group B compared to group A, indicating that drug A is more effective (i.e.&nbsp;lower odds of hospitalization).</p>
</blockquote>
<hr>
</section>
<section id="model-2-cbindy-n---y-diseaseseverity" class="level4">
<h4 class="anchored" data-anchor-id="model-2-cbindy-n---y-diseaseseverity">Model 2: cbind(Y, N - Y) ~ DiseaseSeverity</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>model_2_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cbind</span>(Y, N <span class="sc">-</span> Y) <span class="sc">~</span> DiseaseSeverity,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> hospitalizations</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Again, let’s look at the second model using R’s <code>summary</code> function:</p>
</blockquote>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(Y, N - Y) ~ DiseaseSeverity, family = binomial(link = "logit"), 
    data = hospitalizations)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -0.54903    0.08599  -6.385 1.72e-10 ***
DiseaseSeverity  0.20778    0.08551   2.430   0.0151 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 31.120  on 5  degrees of freedom
Residual deviance: 25.214  on 4  degrees of freedom
AIC: 62.053

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>I also want to interpret these results. There is a significant association between disease severity and hospitalization (p &lt; 0.05). The estimated OR is 1.23, and the 95% confidence interval is [1.04, 1.45]. Thus, for every unit increase in disease severity (continuous scale), the odds of hospitalization increase by 23%.</p>
</blockquote>
<hr>
</section>
<section id="model-3-cbindy-n---y-treatment-diseaseseverity" class="level4">
<h4 class="anchored" data-anchor-id="model-3-cbindy-n---y-treatment-diseaseseverity">Model 3: cbind(Y, N - Y) ~ Treatment * DiseaseSeverity</h4>
<p>We fit the final model below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>model_3_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cbind</span>(Y, N <span class="sc">-</span> Y) <span class="sc">~</span> Treatment <span class="sc">*</span> DiseaseSeverity,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> hospitalizations</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Once again, let’s summarize this model and interpret the result.</p>
</blockquote>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(Y, N - Y) ~ Treatment * DiseaseSeverity, 
    family = binomial(link = "logit"), data = hospitalizations)

Coefficients:
                          Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                -0.9883     0.1473  -6.711 1.94e-11 ***
Treatment                   0.7023     0.1826   3.845  0.00012 ***
DiseaseSeverity             0.5110     0.1305   3.917 8.96e-05 ***
Treatment:DiseaseSeverity  -0.5122     0.1748  -2.931  0.00338 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 31.1203  on 5  degrees of freedom
Residual deviance:  9.8977  on 2  degrees of freedom
AIC: 50.736

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The interaction term is significant! The effect of treatment does vary across different values of disease severity.</p>
</blockquote>
<hr>
<ol start="5" type="a">
<li>What are the degrees of freedom (DF) of deviance under different models? DF of the null deviance:</li>
</ol>
<p>DF of the residual deviance for Model 1:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(DF = n - p = 6 - 2 = 4\)</span></p>
</blockquote>
<p>DF of the residual deviance for Model 2:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(DF = n - p = 6 - 2 = 4\)</span></p>
</blockquote>
<p>DF of the residual deviance for Model 3:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(DF = n - p = 6 - 4 = 2\)</span></p>
</blockquote>
<ol start="6" type="a">
<li>In Model 1, interpret all coefficients. Show how to conduct inference about the association between the treatment and hospitalization. This will answer the scientific question that was paired with Model 1 in (c). Explain fully.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Interpreting Treatment</strong>: Again, the treatment coefficient was signicant (p &lt; 0.05) and the 95% confidence interval for the OR was above 1. The estimated OR is 1.34, indicating that the odds of hospitalization are 34% higher for individuals taking drug B compared to those taking drug B. This indicates that drug A is more favorable.</p>
<p><strong>Interpreting the Intercept</strong>: The intercept is interesting. This coefficient is the log odds of hospitalization when all coefficients are set to zero. For this model, that means that the odds of hospitalization for those taking drug A (i.e.&nbsp;treatment = 0) is 0.557. This indicates that the probability of hospitalization is lower than the probability of not being hospitalized for those taking drug A.</p>
</blockquote>
<ol start="7" type="a">
<li>Answer Question 2. Which model will you use? Interpret the associated model parameters and draw inferences. Explain fully.</li>
</ol>
<blockquote class="blockquote">
<p>Here’s question 2 again: Is the disease severity associated with hospitalization?</p>
<p>Recall that model 2 contains only disease severity as a predictor. Thus, I will use this model to answer the question.</p>
<p><strong>Interpreting Disease Severity</strong>: The 95% confidence for disease severity is [1.04, 1.45], with (p &lt; 0.05). So yes, disease severity is associated with hospitalization. The point estimate for the OR is 1.23, indicating that for every unit increase of disease severity, the odds of hospitalization increase by 23%.</p>
<p><strong>Interpreting the Intercept</strong>: Once again, the intercept coefficient is the log odds of hospitalization given a disease severity value of 0. With a coefficient of -0.549, the estimated odds of hospitalization for individuals with DS = 0 is 0.57.</p>
</blockquote>
<ol start="8" type="a">
<li>In Model 3, what is the odds ratio between two groups: patients having treatment=0 and disease severity=1 vs.&nbsp;patients having treatment=1 and disease severity=2. Calculate the associated 95% confidence interval of the odds ratio.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Pattern 1</strong>: Treatment = 0, Disease Severity = 1.</p>
<p><strong>Pattern 2</strong>: Treatment = 1, Disease Severity = 2.</p>
<p><span class="math inline">\(OR = \exp\left[ (-1)\beta_1 + (-1)\beta_2 + (-2) \beta_3 \right] \implies L^T = [0,-1,-1,-2]\)</span></p>
</blockquote>
<blockquote class="blockquote">
<p>Let’s now calculate our point estimate for the odds ratio:</p>
</blockquote>
<p><span class="math display">\[\begin{align*}
OR &amp;= \exp\left[ (-1)\beta_1 + (-1)\beta_2 + (-2) \beta_3 \right]\\
&amp;= \exp\left[ (-1)(0.70)+ (-1)(0.51) + (-2) (-0.51) \right]\\
&amp;= 0.828
\end{align*}\]</span></p>
<blockquote class="blockquote">
<p>We can use R to calculate the standard error for <span class="math inline">\(\hat{\beta}\)</span>, which will be necessary to calculate a 95% confidence interval:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance-covariance matrix</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>var_cov <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_3_fit)<span class="sc">$</span>cov.unscaled</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify L</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate variance and standard error</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>or_var <span class="ot">&lt;-</span> l <span class="sc">%*%</span> var_cov <span class="sc">%*%</span> <span class="fu">t</span>(l)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>or_stderr <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(or_var)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print standard error</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="st">"Standard Error = "</span>, <span class="fu">round</span>(or_stderr, <span class="dv">3</span>))</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Standard Error = 0.205"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>The 95% confidence interval is given below:</p>
</blockquote>
<p><span class="math display">\[\begin{align*}
95\% \text{ Confidence Interval} &amp;= \hat{OR} \pm Z_{1 - \alpha/2}SE\left( \hat{OR}\right)\\
&amp;= 0.828 \pm 1.96 \cdot 0.205\\
&amp;= [0.425, 1.230]
\end{align*}\]</span></p>
<ol type="i">
<li>Can you answer Question 3 using Model 3? What is your conclusion about Question 3? Explain fully.</li>
</ol>
<blockquote class="blockquote">
<p>Yes, we can!</p>
<p>Recall question 3: Does the treatment effect differ by disease severity? (i.e., Is the disease severity an effect moderator?) This can be answered by looking at the <strong>interaction</strong> between treatment and disease severity. Because this interaction term is significant, we can say that the treatment effect does differ by disease severity.</p>
</blockquote>
<ol start="10" type="a">
<li>We want to compare models using the likelihood ratio test (LRT). Which pairs can be compared using LRT?</li>
</ol>
<blockquote class="blockquote">
<p>Recall that for LRT, we must be comparing <strong>nested</strong> models. Thus, only comparisons of full v nested are eligible:</p>
</blockquote>
<p>Model 1 vs.&nbsp;Model 2 YES NO</p>
<blockquote class="blockquote">
<p>No.&nbsp;Model 1 and Model 2 have different covariates. The predictors of neither is a subset of the predictors of the other.</p>
</blockquote>
<p>Model 1 vs.&nbsp;Model 3 YES NO</p>
<blockquote class="blockquote">
<p>Yes! Model 1 is a special case of model 3 (i.e.&nbsp;all covariates beside Treatment are 0).</p>
</blockquote>
<p>Model 2 vs.&nbsp;Model 3 YES NO</p>
<blockquote class="blockquote">
<p>Yes! Model 2 is a special case of model 3.</p>
</blockquote>
</section>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2">Problem 2</h2>
<p>We want to fit a logistic regression model using the Embryogenic Anther data (see lecture note 4). We consider the following two models:</p>
<p>• Model 1: <span class="math inline">\(logit(P) = β_0 + β_1\text{newstor}\)</span></p>
<p>• Model 2: <span class="math inline">\(logit(P) = β_0 + β_1\text{newstor} + β_2\text{force} + β_3\text{newstor} · \text{force}\)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 18%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Y</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">NewStorage</th>
<th style="text-align: center;">Force</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">55</td>
<td style="text-align: center;">102</td>
<td style="text-align: center;">Control</td>
<td style="text-align: center;">40</td>
</tr>
<tr class="even">
<td style="text-align: center;">52</td>
<td style="text-align: center;">99</td>
<td style="text-align: center;">Control</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">57</td>
<td style="text-align: center;">108</td>
<td style="text-align: center;">Control</td>
<td style="text-align: center;">350</td>
</tr>
<tr class="even">
<td style="text-align: center;">55</td>
<td style="text-align: center;">76</td>
<td style="text-align: center;">Treatment</td>
<td style="text-align: center;">40</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50</td>
<td style="text-align: center;">81</td>
<td style="text-align: center;">Treatment</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">Treatment</td>
<td style="text-align: center;">350</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li>Fit the two models in R or SAS using “grouped” data. Provide your code and output.</li>
</ol>
<blockquote class="blockquote">
<p>Let’s approach this the same way we did in the first problem.</p>
</blockquote>
<hr>
<section id="model-1-logitp-β_0-β_1newstor" class="level4">
<h4 class="anchored" data-anchor-id="model-1-logitp-β_0-β_1newstor">Model 1: <span class="math inline">\(logit(P) = β_0 + β_1newstor\)</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify data</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>force <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">150</span>, <span class="dv">350</span>, <span class="dv">40</span>, <span class="dv">150</span>, <span class="dv">350</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">55</span>, <span class="dv">52</span>, <span class="dv">57</span>, <span class="dv">55</span>, <span class="dv">50</span>, <span class="dv">50</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">102</span>, <span class="dv">99</span>, <span class="dv">108</span>, <span class="dv">76</span>, <span class="dv">81</span>, <span class="dv">90</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>embryogenic <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y =</span> y, <span class="at">n =</span> n, <span class="at">newstor =</span> treatment, <span class="at">force =</span> force)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>model_1_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> newstor,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Let’s now look at the summary:</p>
</blockquote>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(y, n - y) ~ newstor, family = binomial(link = "logit"), 
    data = embryogenic)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)   0.1231     0.1140   1.080   0.2801  
newstor       0.3985     0.1741   2.289   0.0221 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 10.452  on 5  degrees of freedom
Residual deviance:  5.173  on 4  degrees of freedom
AIC: 38.741

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<hr>
</section>
<section id="model-2-logitp-β_0-β_1textnewstor-β_2textforce-β_3textnewstor-textforce" class="level4">
<h4 class="anchored" data-anchor-id="model-2-logitp-β_0-β_1textnewstor-β_2textforce-β_3textnewstor-textforce">Model 2: <span class="math inline">\(logit(P) = β_0 + β_1\text{newstor} + β_2\text{force} + β_3\text{newstor} · \text{force}\)</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>model_2_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> newstor <span class="sc">*</span> force,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(y, n - y) ~ newstor * force, family = binomial(link = "logit"), 
    data = embryogenic)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)    0.1456719  0.1975451   0.737   0.4609  
newstor        0.7963143  0.3125046   2.548   0.0108 *
force         -0.0001227  0.0008782  -0.140   0.8889  
newstor:force -0.0020493  0.0013483  -1.520   0.1285  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 10.45197  on 5  degrees of freedom
Residual deviance:  0.60387  on 2  degrees of freedom
AIC: 38.172

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<hr>
<ol start="2" type="a">
<li>Fit the two models in R or SAS after converting the “grouped” data into “ungrouped” data. Provide your code and output. Compare the results in (a) and (b).</li>
</ol>
<hr>
</section>
<section id="model-1-logitp-β_0-β_1newstor-1" class="level4">
<h4 class="anchored" data-anchor-id="model-1-logitp-β_0-β_1newstor-1">Model 1: <span class="math inline">\(logit(P) = β_0 + β_1newstor\)</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ungroup the data</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>newstor_2 <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">sum</span>(n[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">sum</span>(n[<span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>]))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>force_2 <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">40</span>, n[<span class="dv">1</span>]),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">150</span>, n[<span class="dv">2</span>]),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">350</span>, n[<span class="dv">3</span>]),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">40</span>, n[<span class="dv">4</span>]),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">150</span>, n[<span class="dv">5</span>]),</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">350</span>, n[<span class="dv">6</span>])</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>y_2 <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, y[<span class="dv">1</span>]),</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, n[<span class="dv">1</span>] <span class="sc">-</span> y[<span class="dv">1</span>]),</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, y[<span class="dv">2</span>]),</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, n[<span class="dv">2</span>] <span class="sc">-</span> y[<span class="dv">2</span>]),</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, y[<span class="dv">3</span>]),</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, n[<span class="dv">3</span>] <span class="sc">-</span> y[<span class="dv">3</span>]),</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, y[<span class="dv">4</span>]),</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, n[<span class="dv">4</span>] <span class="sc">-</span> y[<span class="dv">4</span>]),</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, y[<span class="dv">5</span>]),</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, n[<span class="dv">5</span>] <span class="sc">-</span> y[<span class="dv">5</span>]),</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, y[<span class="dv">6</span>]),</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, n[<span class="dv">6</span>] <span class="sc">-</span> y[<span class="dv">6</span>])</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>embryogenic_ungrouped <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> y_2, <span class="at">newstor =</span> newstor_2, <span class="at">force =</span> force_2</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>model_1_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>    y <span class="sc">~</span> newstor,</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic_ungrouped</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ newstor, family = binomial(link = "logit"), 
    data = embryogenic_ungrouped)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)   0.1231     0.1140   1.080   0.2801  
newstor       0.3985     0.1741   2.289   0.0221 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 758.64  on 555  degrees of freedom
Residual deviance: 753.36  on 554  degrees of freedom
AIC: 757.36

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<hr>
</section>
<section id="model-2-logitp-β_0-β_1textnewstor-β_2textforce-β_3textnewstor-textforce-1" class="level4">
<h4 class="anchored" data-anchor-id="model-2-logitp-β_0-β_1textnewstor-β_2textforce-β_3textnewstor-textforce-1">Model 2: <span class="math inline">\(logit(P) = β_0 + β_1\text{newstor} + β_2\text{force} + β_3\text{newstor} · \text{force}\)</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>model_2_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    y <span class="sc">~</span> newstor <span class="sc">*</span> force,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic_ungrouped</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ newstor * force, family = binomial(link = "logit"), 
    data = embryogenic_ungrouped)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)    0.1456719  0.1975451   0.737   0.4609  
newstor        0.7963143  0.3125046   2.548   0.0108 *
force         -0.0001227  0.0008782  -0.140   0.8889  
newstor:force -0.0020493  0.0013483  -1.520   0.1285  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 758.64  on 555  degrees of freedom
Residual deviance: 748.79  on 552  degrees of freedom
AIC: 756.79

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<hr>
</section>
<section id="observations" class="level4">
<h4 class="anchored" data-anchor-id="observations">Observations</h4>
<blockquote class="blockquote">
<p>You’ll notice that for both model 1 and model 2, the coefficients and p-values are equivalent using ungrouped vs grouped data. So, what’s the difference? Well, a lot, actually. The AIC is <strong>vastly</strong> different (757 vs 38 for model 1).</p>
<p>The deviance and degrees of freedom are also different. In fact, the deviance for both the ungrouped data models are less useful than those of the grouped data because</p>
</blockquote>
<ol start="3" type="a">
<li>Conduct a likelihood ratio test comparing the two models using both grouped and ungrouped data. Do they give the same conclusion?</li>
</ol>
<hr>
</section>
<section id="liklihood-ratio-test-grouped-data" class="level4">
<h4 class="anchored" data-anchor-id="liklihood-ratio-test-grouped-data">Liklihood Ratio Test: Grouped Data</h4>
<blockquote class="blockquote">
<p>Note that an important assumption about the LRT is that the models are heirarchical or nested in nature. This is true for both the ungrouped and grouped data analyses.</p>
<p>The other major consideration is how well these data are suited to LR modeling. We can use the Hosmer-Lemeshow test to show this:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit models to make sure we're doing the correct test</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>model_1_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> newstor,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>model_2_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> newstor <span class="sc">*</span> force,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the p-value for the Hosmer-Lemeshow test</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> ResourceSelection<span class="sc">::</span><span class="fu">hoslem.test</span>(</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    model_1_fit<span class="sc">$</span>y, model_1_fit<span class="sc">$</span>fitted.values,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">g =</span> <span class="dv">3</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>t2 <span class="ot">&lt;-</span> ResourceSelection<span class="sc">::</span><span class="fu">hoslem.test</span>(</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    model_2_fit<span class="sc">$</span>y, model_2_fit<span class="sc">$</span>fitted.values,</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">g =</span> <span class="dv">3</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>The p-value for model 1 is 0.991, and the p-value for model 2 is 0.991. Because we <strong>want</strong> to fail to reject the null hypothesis, we can say that we <strong>don’t</strong> have the evidence to suggest that these models do <strong>not</strong> fit the data well. Double negatives are hard, so we’re just saying we can run the test.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Run LRT test</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>deviance_1 <span class="ot">&lt;-</span> model_1_fit<span class="sc">$</span>deviance</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>deviance_2 <span class="ot">&lt;-</span> model_2_fit<span class="sc">$</span>deviance</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> deviance_1 <span class="sc">-</span> deviance_2</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>pval <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(delta, p <span class="sc">-</span> q)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>The p-value from this test is 0.102. Thus, we fail to reject the null hypothesis (but we’ll get to that later).</p>
</blockquote>
<hr>
</section>
<section id="liklihood-ratio-test-ungrouped-data" class="level4">
<h4 class="anchored" data-anchor-id="liklihood-ratio-test-ungrouped-data">Liklihood Ratio Test: Ungrouped Data</h4>
<blockquote class="blockquote">
<p>Like the previous part, these models are nested. So let’s look at the Hosmer-Lemeshow test to make sure we’re okay to move forward.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit models to make sure we're doing the correct test</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>model_1_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    y <span class="sc">~</span> newstor,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic_ungrouped</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>model_2_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    y <span class="sc">~</span> newstor <span class="sc">*</span> force,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> embryogenic_ungrouped</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the p-value for the Hosmer-Lemeshow test</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> ResourceSelection<span class="sc">::</span><span class="fu">hoslem.test</span>(</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    model_1_fit<span class="sc">$</span>y, model_1_fit<span class="sc">$</span>fitted.values,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">g =</span> <span class="dv">3</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>t2 <span class="ot">&lt;-</span> ResourceSelection<span class="sc">::</span><span class="fu">hoslem.test</span>(</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    model_2_fit<span class="sc">$</span>y, model_2_fit<span class="sc">$</span>fitted.values,</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">g =</span> <span class="dv">3</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>The p-value for model 1 is 1, and the p-value for model 2 is 1. Once again, we fail to reject the null hypothesis, which means we can proceed.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">###################################### R ######################################</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Run LRT test</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>deviance_1 <span class="ot">&lt;-</span> model_1_fit<span class="sc">$</span>deviance</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>deviance_2 <span class="ot">&lt;-</span> model_2_fit<span class="sc">$</span>deviance</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> deviance_1 <span class="sc">-</span> deviance_2</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>pval <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(delta, p <span class="sc">-</span> q)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="do">###############################################################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>The p-value from this test is 0.102. This is exactly the same as the previous p-value!</p>
</blockquote>
<hr>
<ol start="4" type="a">
<li>Write a paragraph for a manuscript to describe your likelihood ratio test results (pick one from grouped and ungrouped data). It should include hypotheses, results, and interpretation.</li>
</ol>
<blockquote class="blockquote">
<p>We conducted a likelihood ratio test (LRT) to compare two logistic regression models fitted to the embryogenic anther dataset. The null hypothesis is that Model 1 (which includes only the treatment effect) provides an adequate fit for the data, while the alternative hypothesis is that Model 2 (which includes treatment, force, and their interaction) provides a significantly better fit. Both models were nested, allowing for a valid LRT. For the grouped data, the deviance for Model 1 was 5.17, and for Model 2, it was 0.60. The difference in deviance between the two models was 4.57, with two degrees of freedom. The resulting p-value was 0.1018, indicating that we fail to reject the null hypothesis (p &gt; 0.05). This suggests that the inclusion of the interaction term and the force variable in Model 2 does not significantly improve the model fit compared to Model 1. Therefore, Model 1 may be sufficient to describe the relationship between the treatment and response variables for this dataset.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>